gaits:
  square:
    file_name: 'square-test.csv'
    publish_rate: 250 # Hz
  zero:
    file_name: 'zero.csv'
    publish_rate: 100 # Hz
  swim-test:
    file_name: 'swimtest-7pt.csv'
    publish_rate: 1250 # Hz