gaits:
  square:
    file_name: 'square-test.csv'
    publish_rate: 250 # Hz
  zero:
    file_name: 'zero.csv'
    publish_rate: 100 # Hz
  swim-test:
    file_name: 'swimtest-7pt.csv'
    publish_rate: 1250 # Hz
  walk1-test:
    file_name: 'walktest1-7pt.csv'
    publish_rate: 2500 # Hz
  walk2-test:
    file_name: 'walktest2-7pt.csv'
    publish_rate: 2500 # Hz
  hop-test:
    file_name: 'hop-test.csv'
    publish_rate: 2500 # Hz
  jump-test:
    file_name: 'jump-test.csv'
    publish_rate: 1250 # Hz