square:
  file_name: 'square-test.csv'
  publish_rate: 250 # Hz
zero:
  file_name: 'zero.csv'
  publish_rate: 100 # Hz
hop:
  file_name: 'hop-test.csv'
  publish_rate: 2500 # Hz
jump:
  file_name: 'jump-test.csv'
  publish_rate: 1250 # Hz