# Motor driver configuration for the BOOM

motor0:
  id: 0
  serial_number: "335837603230"
  control_mode: 3
  # zero position
motor1:
  id: 1
  serial_number: "3355375E3230"
  control_mode: 3

# Control Modes
# 1: Torque control
# 2: Velocity control
# 3: Position control
