# Motor driver configuration for the BOOM

motor0:
  id: 0
  serial_number: "335837603230" # USB only
  control_mode: 3
  gear_ratio: 6.0
  # zero position
  # can id
motor1:
  id: 1
  serial_number: "3355375E3230" # USB only
  control_mode: 3
  gear_ratio: 6.0

# Control Modes
# 1: Torque control
# 2: Velocity control
# 3: Position control
