# Motor driver configuration for the BOOM

motor0:
  id: 0
  control_mode: 3
  gear_ratio: 6.0
  can_id: 0
  # zero position
motor1:
  id: 1
  control_mode: 3
  gear_ratio: 6.0
  can_id: 1

# Control Modes
# 1: Torque control
# 2: Velocity control
# 3: Position control
